# Generated by Django 3.1.7 on 2021-03-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='fridge_items',
        ),
    ]
